import { test, expect } from '@playwright/test';
import { HomePage } from '../../pages/HomePage';

/**
 * Visual Regression Tests - Generated by MCP Visual Test Generator
 * Automated screenshot comparison across multiple viewports
 */
test.describe('Visual Testing - Homepage', () => {
  let homePage: HomePage;

  test.beforeEach(async ({ page }) => {
    homePage = new HomePage(page);
    await homePage.goto();
    await homePage.waitForLoad();
  });

  test('homepage visual comparison - desktop @visual', async ({ page }) => {
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.waitForTimeout(1000);
    
    await expect(page).toHaveScreenshot('homepage-desktop.png', {
      fullPage: true,
      threshold: 0.2,
      animations: 'disabled'
    });
  });

  test('homepage visual comparison - tablet @visual', async ({ page }) => {
    await page.setViewportSize({ width: 768, height: 1024 });
    await page.waitForTimeout(1000);
    
    await expect(page).toHaveScreenshot('homepage-tablet.png', {
      fullPage: true,
      threshold: 0.2,
      animations: 'disabled'
    });
  });

  test('homepage visual comparison - mobile @visual', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await page.waitForTimeout(1000);
    
    await expect(page).toHaveScreenshot('homepage-mobile.png', {
      fullPage: true,
      threshold: 0.2,
      animations: 'disabled'
    });
  });

  test('language switcher visual states @visual', async ({ page }) => {
    const languages = ['en', 'de', 'es'];
    
    for (const lang of languages) {
      await homePage.switchLanguage(lang);
      await page.waitForTimeout(500);
      
      await expect(page).toHaveScreenshot(`homepage-${lang}.png`, {
        fullPage: true,
        threshold: 0.3,
        animations: 'disabled'
      });
    }
  });

  test('navigation menu visual states @visual', async ({ page }) => {
    // Test hover states
    await homePage.findOwnersButton.hover();
    await expect(page).toHaveScreenshot('homepage-hover-owners.png', {
      animations: 'disabled'
    });

    await homePage.veterinariansButton.hover();
    await expect(page).toHaveScreenshot('homepage-hover-vets.png', {
      animations: 'disabled'
    });
  });
});
