version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: jira-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jiradb
      POSTGRES_USER: jirauser
      POSTGRES_PASSWORD: deinSicheresPasswort
    ports:
      - "5432:5432"
    volumes:
      - jira-pgdata:/var/lib/postgresql/data

volumes:
  jira-pgdata:
    driver: local
