/**
 * Test Fixtures - Generated by MCP Test Data Manager
 * Realistic PetClinic test data for consistent testing
 */

export const testOwners = [
  {
    id: 1,
    firstName: 'Max',
    lastName: 'Mustermann',
    address: 'Musterstraße 123',
    city: 'Berlin',
    telephone: '030-12345678'
  },
  {
    id: 2,
    firstName: 'Anna',
    lastName: 'Schmidt',
    address: 'Beispielweg 456',
    city: 'München',
    telephone: '089-87654321'
  },
  {
    id: 3,
    firstName: 'John',
    lastName: 'Doe',
    address: '123 Main Street',
    city: 'New York',
    telephone: '555-0123'
  }
];

export const testPetTypes = [
  { id: 1, name: 'cat' },
  { id: 2, name: 'dog' },
  { id: 3, name: 'lizard' },
  { id: 4, name: 'snake' },
  { id: 5, name: 'bird' },
  { id: 6, name: 'hamster' }
];

export const testPets = [
  {
    id: 1,
    name: 'Fluffy',
    birthDate: '2020-05-15',
    type: testPetTypes[0], // cat
    owner: testOwners[0]
  },
  {
    id: 2,
    name: 'Buddy',
    birthDate: '2019-03-22',
    type: testPetTypes[1], // dog
    owner: testOwners[1]
  },
  {
    id: 3,
    name: 'Scales',
    birthDate: '2021-01-10',
    type: testPetTypes[3], // snake
    owner: testOwners[2]
  }
];

export const testVisits = [
  {
    id: 1,
    date: '2025-01-15',
    description: 'Regular checkup',
    pet: testPets[0]
  },
  {
    id: 2,
    date: '2025-02-20',
    description: 'Vaccination',
    pet: testPets[1]
  }
];

/**
 * Language test data for multilingual testing
 */
export const languageTestData = {
  en: {
    welcome: 'Welcome',
    findOwners: 'FIND OWNERS',
    veterinarians: 'VETERINARIANS'
  },
  de: {
    welcome: 'Willkommen',
    findOwners: 'BESITZER FINDEN',
    veterinarians: 'TIERÄRZTE'
  },
  es: {
    welcome: 'Bienvenido',
    findOwners: 'BUSCAR PROPIETARIOS',
    veterinarians: 'VETERINARIOS'
  },
  pt: {
    welcome: 'Bem-vindo',
    findOwners: 'ENCONTRAR PROPRIETÁRIOS',
    veterinarians: 'VETERINÁRIOS'
  }
};

/**
 * Mobile test data
 */
export const mobileTestData = {
  viewports: {
    iphone12: { width: 390, height: 844 },
    ipadPro: { width: 1024, height: 1366 },
    galaxyS21: { width: 360, height: 800 }
  },
  touchTargets: {
    minSize: 44, // Minimum touch target size in pixels
    spacing: 8   // Minimum spacing between touch targets
  }
};

/**
 * API test data
 */
export const apiTestData = {
  validOwner: {
    firstName: 'Test',
    lastName: 'User',
    address: '123 Test Street',
    city: 'Test City',
    telephone: '555-TEST'
  },
  invalidOwner: {
    firstName: '',
    lastName: '',
    address: '',
    city: '',
    telephone: ''
  },
  validPetType: {
    name: 'TestPet'
  },
  invalidPetType: {
    name: ''
  }
};

/**
 * Performance test thresholds
 */
export const performanceThresholds = {
  pageLoadTime: 3000,      // 3 seconds
  apiResponseTime: 1000,    // 1 second
  navigationTime: 500,      // 500ms
  imageLoadTime: 2000       // 2 seconds
};
